### PR TITLE
Seer race

### PR DESCRIPTION
**Pull request by scajina**
Added Seer race to the hero loader.

### CODE REVIEW

**Comment by giero** [comment]
@scajina Thanks :)

**Comment by scajina** [comment]
Thanks! Hoping to contribute more in the future!

**Comment by njb1966** [comment]
Seer race is still not recognized. Causing updates to the spreadsheet to error out and not update.

**Comment by njb1966** [comment]
I looked and Seer should not be listed under "race" it should be in the line with Balanced, Attacker, etc.... this is why it won't update.

**Pull request merged**
